spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=smart_banking
    username: postgres
    password: root
  devtools:
    add-properties: false
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgresSQL8Dialect