spring:
  datasource:
    url: jdbc:postgresql://smart-bank-db-tharukagayashan1.a.aivencloud.com:16735/defaultdb?currentSchema=smart-bank
    username: avnadmin
    password: AVNS_BIViiL_nM5dJXJXupPU
  devtools:
    add-properties: false
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgresSQL8Dialect