CREATE SEQUENCE IF NOT EXISTS BN_R_ACCOUNT_TYPE_SEQ START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS BN_R_BANK_SEQ START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS BN_R_BRANCH_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS BN_R_CHARGE_SEQ START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS BN_R_CURRENCY_SEQ START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS BN_R_FEE_TYPE_SEQ START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS BN_R_INT_RATE_SEQ START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS BN_R_LOAN_PERIOD_SEQ START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS BN_R_LOAN_PRODUCT_SEQ START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS BN_R_LOAN_TYPE_SEQ START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS BN_R_STATUS_SEQ START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS BN_R_TRAN_TYPE_SEQ START WITH 1 INCREMENT BY 50;

CREATE TABLE BN_R_ACCOUNT_TYPE
(
    ACCOUNT_TYPE_ID   BIGINT NOT NULL,
    CREATED_BY        VARCHAR(255),
    UPDATED_BY        VARCHAR(255),
    CREATED_ON        TIMESTAMP WITHOUT TIME ZONE,
    UPDATED_ON        TIMESTAMP WITHOUT TIME ZONE,
    ACCOUNT_TYPE_NAME VARCHAR(50),
    ACCOUNT_TYPE_CODE VARCHAR(5),
    CONSTRAINT PK_BN_R_ACCOUNT_TYPE PRIMARY KEY (ACCOUNT_TYPE_ID)
);

CREATE TABLE BN_R_BANK
(
    BANK_ID    BIGINT NOT NULL,
    CREATED_BY VARCHAR(255),
    UPDATED_BY VARCHAR(255),
    CREATED_ON TIMESTAMP WITHOUT TIME ZONE,
    UPDATED_ON TIMESTAMP WITHOUT TIME ZONE,
    BANK_NAME  VARCHAR(45),
    BANK_CODE  VARCHAR(5),
    IS_ACTIVE  BOOLEAN,
    CONSTRAINT PK_BN_R_BANK PRIMARY KEY (BANK_ID)
);

CREATE TABLE BN_R_BRANCH
(
    BRANCH_ID   BIGINT NOT NULL,
    CREATED_BY  VARCHAR(255),
    UPDATED_BY  VARCHAR(255),
    CREATED_ON  TIMESTAMP WITHOUT TIME ZONE,
    UPDATED_ON  TIMESTAMP WITHOUT TIME ZONE,
    BRANCH_NAME VARCHAR(50),
    BRANCH_CODE VARCHAR(5),
    IS_ACTIVE   BOOLEAN,
    BANK_ID     BIGINT NOT NULL,
    CONSTRAINT PK_BN_R_BRANCH PRIMARY KEY (BRANCH_ID)
);

CREATE TABLE BN_R_CHARGE
(
    CHARGE_ID       BIGINT NOT NULL,
    CREATED_BY      VARCHAR(255),
    UPDATED_BY      VARCHAR(255),
    CREATED_ON      TIMESTAMP WITHOUT TIME ZONE,
    UPDATED_ON      TIMESTAMP WITHOUT TIME ZONE,
    CHARGE_DESC     VARCHAR(100),
    AMOUNT          FLOAT,
    EFFECTIVE_DATE  DATE,
    EXPIRATION_DATE DATE,
    FEE_TYPE_ID     BIGINT NOT NULL,
    CURRENCY_ID     BIGINT NOT NULL,
    CONSTRAINT PK_BN_R_CHARGE PRIMARY KEY (CHARGE_ID)
);

CREATE TABLE BN_R_CURRENCY
(
    CURRENCY_ID   BIGINT NOT NULL,
    CREATED_BY    VARCHAR(255),
    UPDATED_BY    VARCHAR(255),
    CREATED_ON    TIMESTAMP WITHOUT TIME ZONE,
    UPDATED_ON    TIMESTAMP WITHOUT TIME ZONE,
    CURRENCY_NAME VARCHAR(45),
    CURRENCY_CODE VARCHAR(5),
    CONSTRAINT PK_BN_R_CURRENCY PRIMARY KEY (CURRENCY_ID)
);

CREATE TABLE BN_R_FEE_TYPE
(
    FEE_TYPE_ID   BIGINT NOT NULL,
    CREATED_BY    VARCHAR(255),
    UPDATED_BY    VARCHAR(255),
    CREATED_ON    TIMESTAMP WITHOUT TIME ZONE,
    UPDATED_ON    TIMESTAMP WITHOUT TIME ZONE,
    FEE_TYPE_NAME VARCHAR(45),
    FEE_TYPE_DESC VARCHAR(100),
    CONSTRAINT PK_BN_R_FEE_TYPE PRIMARY KEY (FEE_TYPE_ID)
);

CREATE TABLE BN_R_INT_RATE
(
    INT_RATE_ID   BIGINT NOT NULL,
    CREATED_BY    VARCHAR(255),
    UPDATED_BY    VARCHAR(255),
    CREATED_ON    TIMESTAMP WITHOUT TIME ZONE,
    UPDATED_ON    TIMESTAMP WITHOUT TIME ZONE,
    INT_RATE_NAME VARCHAR(45),
    INT_RATE_DESC VARCHAR(100),
    RATE          FLOAT,
    CONSTRAINT PK_BN_R_INT_RATE PRIMARY KEY (INT_RATE_ID)
);

CREATE TABLE BN_R_LOAN_PERIOD
(
    LOAN_PERIOD_ID   BIGINT NOT NULL,
    CREATED_BY       VARCHAR(255),
    UPDATED_BY       VARCHAR(255),
    CREATED_ON       TIMESTAMP WITHOUT TIME ZONE,
    UPDATED_ON       TIMESTAMP WITHOUT TIME ZONE,
    LOAN_PERIOD_NAME VARCHAR(45),
    LOAN_PERIOD_DESC VARCHAR(100),
    MONTH            INTEGER,
    CONSTRAINT PK_BN_R_LOAN_PERIOD PRIMARY KEY (LOAN_PERIOD_ID)
);

CREATE TABLE BN_R_LOAN_PRODUCT
(
    LOAN_PRODUCT_ID BIGINT NOT NULL,
    CREATED_BY      VARCHAR(255),
    UPDATED_BY      VARCHAR(255),
    CREATED_ON      TIMESTAMP WITHOUT TIME ZONE,
    UPDATED_ON      TIMESTAMP WITHOUT TIME ZONE,
    LOAN_TYPE_ID    BIGINT NOT NULL,
    INT_RATE_ID     BIGINT NOT NULL,
    LOAN_PERIOD_ID  BIGINT NOT NULL,
    CONSTRAINT PK_BN_R_LOAN_PRODUCT PRIMARY KEY (LOAN_PRODUCT_ID)
);

CREATE TABLE BN_R_LOAN_TYPE
(
    LOAN_TYPE_ID   BIGINT NOT NULL,
    CREATED_BY     VARCHAR(255),
    UPDATED_BY     VARCHAR(255),
    CREATED_ON     TIMESTAMP WITHOUT TIME ZONE,
    UPDATED_ON     TIMESTAMP WITHOUT TIME ZONE,
    LOAN_TYPE_NAME VARCHAR(50),
    LOAN_TYPE_CODE VARCHAR(5),
    LOAN_TYPE_DESC VARCHAR(100),
    CONSTRAINT PK_BN_R_LOAN_TYPE PRIMARY KEY (LOAN_TYPE_ID)
);

CREATE TABLE BN_R_STATUS
(
    STATUS_ID   BIGINT NOT NULL,
    CREATED_BY  VARCHAR(255),
    UPDATED_BY  VARCHAR(255),
    CREATED_ON  TIMESTAMP WITHOUT TIME ZONE,
    UPDATED_ON  TIMESTAMP WITHOUT TIME ZONE,
    STATUS_NAME VARCHAR(45),
    STATUS_CODE VARCHAR(5),
    STATUS_TYPE VARCHAR(45),
    CONSTRAINT PK_BN_R_STATUS PRIMARY KEY (STATUS_ID)
);

CREATE TABLE BN_R_TRAN_TYPE
(
    TRAN_TYPE_ID   BIGINT NOT NULL,
    CREATED_BY     VARCHAR(255),
    UPDATED_BY     VARCHAR(255),
    CREATED_ON     TIMESTAMP WITHOUT TIME ZONE,
    UPDATED_ON     TIMESTAMP WITHOUT TIME ZONE,
    TRAN_TYPE_NAME VARCHAR(45),
    TRAN_TYPE_CODE VARCHAR(5),
    CONSTRAINT PK_BN_R_TRAN_TYPE PRIMARY KEY (TRAN_TYPE_ID)
);

ALTER TABLE BN_R_ACCOUNT_TYPE
    ADD CONSTRAINT UC_BN_R_ACCOUNT_TYPE_ACCOUNT_TYPE_CODE UNIQUE (ACCOUNT_TYPE_CODE);

ALTER TABLE BN_R_BANK
    ADD CONSTRAINT UC_BN_R_BANK_BANK_CODE UNIQUE (BANK_CODE);

ALTER TABLE BN_R_BRANCH
    ADD CONSTRAINT UC_BN_R_BRANCH_BRANCH_CODE UNIQUE (BRANCH_CODE);

ALTER TABLE BN_R_CURRENCY
    ADD CONSTRAINT UC_BN_R_CURRENCY_CURRENCY_CODE UNIQUE (CURRENCY_CODE);

ALTER TABLE BN_R_LOAN_TYPE
    ADD CONSTRAINT UC_BN_R_LOAN_TYPE_LOAN_TYPE_CODE UNIQUE (LOAN_TYPE_CODE);

ALTER TABLE BN_R_STATUS
    ADD CONSTRAINT UC_BN_R_STATUS_STATUS_CODE UNIQUE (STATUS_CODE);

ALTER TABLE BN_R_TRAN_TYPE
    ADD CONSTRAINT UC_BN_R_TRAN_TYPE_TRAN_TYPE_CODE UNIQUE (TRAN_TYPE_CODE);

CREATE UNIQUE INDEX BN_R_ACCOUNT_TYPE_ACCOUNT_TYPE_CODE_IDX ON BN_R_ACCOUNT_TYPE (ACCOUNT_TYPE_CODE);

CREATE UNIQUE INDEX BN_R_BANK_BANK_CODE_IDX ON BN_R_BANK (BANK_CODE);

CREATE UNIQUE INDEX BN_R_BRANCH_BRANCH_CODE_IDX ON BN_R_BRANCH (BRANCH_CODE);

CREATE UNIQUE INDEX BN_R_CURRENCY_CURRENCY_CODE_IDX ON BN_R_CURRENCY (CURRENCY_CODE);

CREATE UNIQUE INDEX BN_R_LOAN_TYPE_LOAN_TYPE_CODE_IDX ON BN_R_LOAN_TYPE (LOAN_TYPE_CODE);

CREATE UNIQUE INDEX BN_R_STATUS_STATUS_CODE_IDX ON BN_R_STATUS (STATUS_CODE);

CREATE UNIQUE INDEX BN_R_TRAN_TYPE_TRAN_TYPE_CODE_IDX ON BN_R_TRAN_TYPE (TRAN_TYPE_CODE);

ALTER TABLE BN_R_BRANCH
    ADD CONSTRAINT FK_BN_R_BRANCH_ON_BANK FOREIGN KEY (BANK_ID) REFERENCES BN_R_BANK (BANK_ID);

CREATE INDEX BN_R_BRANCH_BANK_ID_IDX ON BN_R_BRANCH (BANK_ID);

ALTER TABLE BN_R_CHARGE
    ADD CONSTRAINT FK_BN_R_CHARGE_ON_CURRENCY FOREIGN KEY (CURRENCY_ID) REFERENCES BN_R_CURRENCY (CURRENCY_ID);

CREATE INDEX BN_R_CHARGE_CURRENCY_ID_IDX ON BN_R_CHARGE (CURRENCY_ID);

ALTER TABLE BN_R_CHARGE
    ADD CONSTRAINT FK_BN_R_CHARGE_ON_FEE_TYPE FOREIGN KEY (FEE_TYPE_ID) REFERENCES BN_R_FEE_TYPE (FEE_TYPE_ID);

CREATE INDEX BN_R_CHARGE_FEE_TYPE_ID_IDX ON BN_R_CHARGE (FEE_TYPE_ID);

ALTER TABLE BN_R_LOAN_PRODUCT
    ADD CONSTRAINT FK_BN_R_LOAN_PRODUCT_ON_INT_RATE FOREIGN KEY (INT_RATE_ID) REFERENCES BN_R_INT_RATE (INT_RATE_ID);

CREATE INDEX BN_R_LOAN_PRODUCT_INT_RATE_ID_IDX ON BN_R_LOAN_PRODUCT (INT_RATE_ID);

ALTER TABLE BN_R_LOAN_PRODUCT
    ADD CONSTRAINT FK_BN_R_LOAN_PRODUCT_ON_LOAN_PERIOD FOREIGN KEY (LOAN_PERIOD_ID) REFERENCES BN_R_LOAN_PERIOD (LOAN_PERIOD_ID);

CREATE INDEX BN_R_LOAN_PRODUCT_LOAN_PERIOD_ID_IDX ON BN_R_LOAN_PRODUCT (LOAN_PERIOD_ID);

ALTER TABLE BN_R_LOAN_PRODUCT
    ADD CONSTRAINT FK_BN_R_LOAN_PRODUCT_ON_LOAN_TYPE FOREIGN KEY (LOAN_TYPE_ID) REFERENCES BN_R_LOAN_TYPE (LOAN_TYPE_ID);

CREATE INDEX BN_R_LOAN_PRODUCT_LOAN_TYPE_ID_IDX ON BN_R_LOAN_PRODUCT (LOAN_TYPE_ID);